# Based on the cirrus example.
container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

test_task:
  env:
    - CODECOV_TOKEN: ENCRYPTED[534076e5934c38da40279df5b57569586a029f455a2a2bf00fbae6ae24bd9df40b9a23102a40cfe175619346d2f9b912]
  modules_cache:
    populate_script: make --debug install_deps
    fingerprint_script: cat go.sum && go version
    folder: $GOPATH/pkg/mod
  build_script: make --debug all
  test_script: make --debug junit-regtest TESTCOVERPROFILE=coverprofile
  always:
    junit_result_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
      type: text/xml

fuzz_test_task:
  modules_cache:
    populate_script: make --debug install_deps
    fingerprint_script: cat go.sum && go version
    folder: $GOPATH/pkg/mod
  test_script: echo ${OUT} && make --debug CXX=clang LIB_FUZZING_ENGINE=-fsanitize=fuzzer fuzz-regtest
  container:
    image: gcr.io/oss-fuzz-base/base-builder

docker_builder:
  name: container_build
  build_script: make --debug container

release_task:
  depends_on:
    - test
    - container_build
    - fuzz_test
  only_if: $CIRRUS_TAG =~ 'v.*'
  env:
    - GITHUB_TOKEN: ENCRYPTED[d81bdfa3956148455e9a5de062e25e4e4bd9cb3031bc577d0d7e3652f3d5cf09d66b6fe9edbd739ce39210558d9b8ae3]
  modules_cache:
    populate_script: make --debug install_deps
    fingerprint_script: cat go.sum && go version
    folder: $GOPATH/pkg/mod
  build_script: |
    make --debug crossbuild
    sha1sum build/*
  upload_script: |
    go get github.com/tcnksm/ghr
    ghr -t ${GITHUB_TOKEN} -u ${CIRRUS_REPO_OWNER} -r ${CIRRUS_REPO_NAME} --replace ${CIRRUS_TAG?} build/
